// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEniuiewUPx35eoUpZqYOzhfvPAHgI0A',
    appId: '1:483360154993:web:358f532d727fdd957382d0',
    messagingSenderId: '483360154993',
    projectId: 'maw-ed',
    authDomain: 'maw-ed.firebaseapp.com',
    storageBucket: 'maw-ed.firebasestorage.app',
    measurementId: 'G-9GK9YRRWQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpDfW2c518AyAp2FaFQyBhLDdVvP_p0A',
    appId: '1:483360154993:android:6156c4e4b86bf8c07382d0',
    messagingSenderId: '483360154993',
    projectId: 'maw-ed',
    storageBucket: 'maw-ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMRL2AlZa_2WT_Z4XAuQIdt0wJs37msVs',
    appId: '1:483360154993:ios:372db55a2ab83b667382d0',
    messagingSenderId: '483360154993',
    projectId: 'maw-ed',
    storageBucket: 'maw-ed.firebasestorage.app',
    iosBundleId: 'com.example.maw3ed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJEniuiewUPx35eoUpZqYOzhfvPAHgI0A',
    appId: '1:483360154993:web:9f07a3741c337dae7382d0',
    messagingSenderId: '483360154993',
    projectId: 'maw-ed',
    authDomain: 'maw-ed.firebaseapp.com',
    storageBucket: 'maw-ed.firebasestorage.app',
    measurementId: 'G-F6M43GY252',
  );
}
